version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, go]
    commit-message:
      prefix: "deps(go):"

  - package-ecosystem: pip
    directory: /services
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, python]
    commit-message:
      prefix: "deps(python):"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, web]
    commit-message:
      prefix: "deps(web):"

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, docker]
    commit-message:
      prefix: "deps(docker):"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, ci]
    commit-message:
      prefix: "deps(ci):"
