{{- if and .Values.postgresql.external.enabled .Values.postgresql.external.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "bamf.fullname" . }}-database-credentials
  labels:
    {{- include "bamf.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.postgresql.external.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.postgresql.external.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "bamf.fullname" . }}-database-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.postgresql.external.externalSecret.remoteRef.key }}
        property: {{ .Values.postgresql.external.externalSecret.remoteRef.property }}
{{- end }}
