{{- if .Values.bridge.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "bamf.fullname" . }}-bridge
  labels:
    {{- include "bamf.labels" . | nindent 4 }}
    app.kubernetes.io/component: bridge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "bamf.fullname" . }}-bridge
  minReplicas: {{ .Values.bridge.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.bridge.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.bridge.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.bridge.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
