{{- if .Values.postgresql.bundled.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bamf.fullname" . }}-postgresql
  labels:
    {{- include "bamf.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: tcp-postgresql
      protocol: TCP
      name: tcp-postgresql
  selector:
    {{- include "bamf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
