{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bamf.fullname" . }}-bridge
  labels:
    {{- include "bamf.labels" . | nindent 4 }}
    app.kubernetes.io/component: bridge
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "bamf.bridge.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: health
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
